spring:
  application:
    name: ms-cards
  cloud:
    function:
      definition: transformFunction;limitCheckFunction;statusCheckFunction;responseFunction;eventSourceFunction
    config:
      enabled: false
    stream:
      bindings:
        transformFunction-in-0:
          destination: payments/credit-cards/initiate,payments/credit-cards/updated,payments/credit-cards/deleted
          group: ms-cards-group
        transformFunction-out-0:
          destination: payments/credit-cards/notification
        limitCheckFunction-in-0:
          destination: payments/credit-cards/validate
          group: ms-cards-limit
        limitCheckFunction-out-0:
          destination: payments/credit-cards/validation/response
        statusCheckFunction-in-0:
          destination: payments/credit-cards/validate
          group: ms-cards-status
        statusCheckFunction-out-0:
          destination: payments/credit-cards/validation/response
        responseFunction-in-0:
          destination: payments/credit-cards/validation/response
          group: ms-validation-response
        eventSourceFunction-in-0:
          destination: payments/credit-cards
          group: ms-slurper
      solace:
        bindings:
          eventSourceFunction-in-0:
            consumer:
              provisionDurableQueue: true
              queue-additional-subscriptions:
                - payments/credit-cards/*
      binders:
        solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55554
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
                ssl:
                  validateCertificate: false
                  validateCertificateChain: false
                  validateHostName: false
                  validateCertificateDate: false
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/domestic_payments?authSource=admin
      database: domestic_payments
  docker:
    compose:
      enabled: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
server:
  port: 80
  servlet:
    context-path: /api/payments/v1
openai:
  api:
    key: ${OPENAI_API_KEY}
solace:
  java:
    host: tcp://localhost:55554
    msgVpn: default
    clientUsername: admin
    clientPassword: admin

encrypt:
  key: ${ENCRYPT_KEY}
  salt: ${ENCRYPT_SALT}
grpc:
  server:
    port: 9090