spring:
  application:
    name: ms-cards
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: domestic_payments
  docker:
    compose:
      enabled: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
server:
  port: 8080
  servlet:
    context-path: /api/payments/v1
