spring:
  application:
    name: ms-cards
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: domestic_payments
  docker:
    compose:
      enabled: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
server:
  port: 8080
  servlet:
    context-path: /api/payments/v1
openai:
  api:
    key: ${OPENAI_API_KEY}
solace:
  java:
    host: tcps://mr-connection-reun98uax5e.messaging.solace.cloud:55443
    msgVpn: ms-cards
    clientUsername: ${SOLACE_USERNAME}
    clientPassword: ${SOLACE_PASSWORD}